### PR TITLE
Updated for Swift 4.1

### PR DESCRIPTION
**Pull request by GioPalusa**

### CODE REVIEW

**Comment by GioPalusa** [comment]
IndexDistance has been removed from Swift since Swift 4.1 which means a lot of this code is deprecated.

Here's some updated code for Swift 4.1 (Line 186, 187 && 189)

internal struct BytesSequence<D: RandomAccessCollection>: Sequence where D.Iterator.Element == UInt8, D.Index == Int {
    let chunkSize: D.Index
    let data: D
    func makeIterator() -> AnyIterator<D.SubSequence> {
        var offset = data.startIndex
        return AnyIterator {
            let end = Swift.min(self.chunkSize, self.data.count - offset)
            let result = self.data[offset..<offset + end]
            offset = offset.advanced(by: result.count)
            if !result.isEmpty {
                return result
            }
            return nil
        }
    }
}
Also deinitialize and deallocate has been redone. This is the updated code for Swift 4.1 (Line 143 && 144)

valuePointer.deinitialize(count: 1)
valuePointer.deallocate()

**Comment by arguiot** [comment]
First of all, thank you very much for your Pull Request 😊.

But I’m getting a few errors when I try to compile your code:
```
swiftc SHA256/swift/hash.swift -o out
SHA256/swift/hash.swift:146:33: error: missing argument for parameter 'capacity' in call
        valuePointer.deallocate()
                                ^
                                capacity: <#Int#>
Swift.UnsafeMutablePointer:273:17: note: 'deallocate(capacity:)' declared here
    public func deallocate(capacity: Int)
                ^
SHA256/swift/hash.swift:195:65: error: binary operator '-' cannot be applied to operands of type 'D.IndexDistance' and 'Int'
            let end = Swift.min(self.chunkSize, self.data.count - offset)
                                                ~~~~~~~~~~~~~~~ ^ ~~~~~~
SHA256/swift/hash.swift:195:65: note: overloads for '-' exist with these partially matching parameter lists: (Int, Int), (UnsafeMutablePointer<Pointee>, Int), (UnsafePointer<Pointee>, Int)
            let end = Swift.min(self.chunkSize, self.data.count - offset)
                                                                ^
```

**Comment by GioPalusa** [comment]
Sorry for the slow response :)
This might be because of an old version of swift. Since Swift 4.1 these have been deprecated and this is the notes from that part. 

> 'deinitialize()' is deprecated: the default argument to deinitialize(count:) has been removed, please specify the count explicitly

> 'deallocate(capacity:)' is deprecated: Swift currently only supports freeing entire heap blocks, use deallocate() instead

> 'IndexDistance' is deprecated: all index distances are now of type Int

**Comment by arguiot** [comment]
I fixed the issue with Travis. Thank you very much for contributing 😊

**Pull request merged**
